#!/bin/bash
#
# Common aliases
#
# @package profile
# @author  Martin Proffitt <mproffitt@choclab.net>
# @link    http://www.choclab.net/
#
for file in $(ls ~/.bashprofile/alias-modules/ | grep -v 'disabled\|README') ; do
    source ~/.bashprofile/alias-modules/$file;
done

##
# Show all defined functions
alias lfunc='typeset -F | sed s/declare\ \-f\ //g';

##
# Run update-modules script
alias update-modules='~/bin/update-modules.bash';

##
# Better clear
alias clear='perl -e "print \"\n\"x512;" && /usr/bin/clear';

##
# Give me some space (partial clear)
alias gimmespace='perl -e "print \"\n\"x20;"';

##
# Load rundeck
#alias rundeck='cd ~/apps/rundeck && nohup tools/bin/run';
alias rundeck='cd ~/apps/rundeck && nohup java -jar rundeck-launcher-1.6.2.jar > ~/logs/rundeck.log 2>&1 &';

if [ $(uname -o) = 'Darwin' ] ; then
  ##
  # tmux alias
  alias tmux="TERM=screen-256color-bce tmux";
fi

##
# Burp
alias burp="nohup java -jar -Xmx1g ${HOME}/apps/burp.jar &>/dev/null &"

##
# onto
alias o='onto'

##
# Search
alias s='search';

##
# Alias for the migflow application (NOT SHARED)
alias tigflow=$HOME'/src/tigflow/tigflow';

##
# Alias for the tigflow application (NOT SHARED)
alias migflow=$HOME'/src/migflow/build/src/migflow';

##
# Alias for radeontop -c
alias radeontop='/usr/sbin/radeontop -c'

##
# Alias for search
alias s='search';

##
# Alias for waitssh
alias ws='waitssh'

##
# Alias to re-ip VirtualBox interface if broken
alias rvbnet='vboxmanage hostonlyif vboxnet0 --ip 192.168.56.1'

##
# Alias to link resolv.conf to /run/resolvconf/resolv.conf
alias rescon='sudo ln -sf /run/resolvconf/resolv.conf /etc/resolv.conf && ls -al /etc/resolv.conf'

##
# alias for ls
alias ls='ls --color=auto'

##
# alias for proxy
alias p='proxy'

##
# alias for noproxy
alias np='noproxy'

##
# Create a random 20 character password and add to clipboard
alias pw='echo -n $(pwgen -synr \`\"\\ 20 1) | xclip -sel clip'

alias dxccon="sudo bash -c 'deveng d; deveng'"
alias dxcdis="sudo bash -c 'deveng d'"

alias tiller="kubectl describe secret \$(kubectl get secrets | grep 'stack-token\|tiller' | awk '{print \$1}') | grep '^token:' | awk '{print \$2}' | xclip -sel clip"
alias dashboard="kubectl port-forward -n kube-system service/kubernetes-dashboard 8080:443 &>/dev/null & tiller"
alias vaultconsul="kubectl port-forward -n vault service/sec-isecops-control-stack-consul-consul-ui 8081:443 &>/dev/null &"
