#!/bin/bash
#
# Common aliases
#
# @package profile
# @author  Martin Proffitt <mproffitt@jitsc.co.uk>
# @link    http://www.jitsc.co.uk/
#

for file in $(ls ~/.profile/alias-parts/ | grep -v 'disabled') ; do
    source ~/.profile/alias-parts/$file;
done

##
# Reload bash_profile
alias resource='clear && . ~/.bash_profile';

##
# Show all defined functions
alias functions='typeset -F | sed s/declare\ \-f\ //g';

##
# Run update-modules script
alias update-modules='~/bin/update-modules.bash';

##
# Better clear
alias clear='perl -e "print \"\n\"x512;" && /usr/bin/clear';

##
# Give me some space (partial clear)
alias gimmespace='perl -e "print \"\n\"x20;"';

##
# Load rundeck
#alias rundeck='cd ~/apps/rundeck && nohup tools/bin/run';
alias rundeck='cd ~/apps/rundeck && nohup java -jar rundeck-launcher-1.6.2.jar > ~/logs/rundeck.log 2>&1 &';

##
# tmux alias
#alias tmux="TERM=screen-256color-bce tmux";

##
# Burp
alias burp='nohup java -jar -Xmx1g /home/mproffitt/apps/burp.jar &>/dev/null &'

##
# onto
alias o='onto'

alias w='waitssh';
alias ws='waitssh';
