#!/bin/bash
#
# Load bash completion helpers
#
# @package profile
# @author  Martin Proffitt <mproffitt@choclab.net>
# @link    http://www.choclab.net/

if [ -f /usr/local/bin/git-flow-completion.bash ]; then
    # Source GitFlow completion
    source /usr/local/bin/git-flow-completion.bash
fi

for file in $(ls ~/.bashprofile/completion-modules/ | grep -v 'disabled\|README') ; do
    source ~/.bashprofile/completion-modules/$file;
done
source <(flux completion bash)
