#!/bin/bash
#
# Load bash completion helpers
#
# @package profile
# @author  Martin Proffitt <mproffitt@jitsc.co.uk>
# @link    http://www.jitsc.co.uk/


for file in $(ls ~/.profile/completion-parts/ | grep -v 'disabled') ; do
    source ~/.profile/completion-parts/$file;
done